train_batch_size: 2
val_batch_size: 20
test_batch_size: 2

num_epochs: 200
lr: .001

optimizer: 'Adam'

# After how many epochs to save the model
save_epoch: 1

model_name: 'vsgnet'

best_model_selection_key : 'val_combined_mAP_all'


GNN: 'GCN'

overfit: False

model_saving_path: '/workspace/work/results_ICRA_vsgnet/'

aggregator : 'mean'

# field to distinguish from different datasets (depending on gif length)
dataset_description: 'vsgnet_dataset'

# root folder of the dataset
dataset_location: '/workspace/data/data_folder/o2o/ral_features/formatted_features/ican'
split_dict_location: '/workspace/data/data_folder/o2o/split_dict.pkl'

# relative location of the annotations file
device: 'cuda:3'

gif_size: 11

loss_calculation: 'masked loss vsgnet'
comments: 'None'

# wandb_configs
wandb_project_name: 'icra_submission_vsgnet'
wandb_entity: 'aunmesh'

log_results: False

roi_pool_size: [10, 10]
spatial_scale: 1
sampling_ratio: 1


# Neural Network dimensions
gnn_dimensions : [1024, 1024]

spatial_branch_cr_classifier_dimension : [512, 3]
spatial_branch_lr_classifier_dimension : [512, 5]
spatial_branch_mr_classifier_dimension : [512, 14]

graphical_branch_cr_classifier_dimension : [1024, 3]
graphical_branch_lr_classifier_dimension : [1024, 5]
graphical_branch_mr_classifier_dimension : [1024, 14]

refined_branch_cr_classifier_dimension : [512, 3]
refined_branch_lr_classifier_dimension : [512, 5]
refined_branch_mr_classifier_dimension : [512, 14]


streams: ['graphical', 'refined', 'spatial', 'combined']
gnn_dropout : 0.00