train_batch_size: 32
val_batch_size: 103
test_batch_size: 102

num_epochs: 200
lr: .001

optimizer: 'Adam'

# After how many epochs to save the model
save_epoch: 1

model_name: 'ican'

overfit: False

model_saving_path: '/workspace/work/results_ICRA_ican/'

aggregator : 'mean'

# field to distinguish from different datasets (depending on gif length)
dataset_description: 'vsgnet_dataset'

split_file_loc: '/workspace/data/data_folder/o2o/split_dict.pkl'
# root folder of the dataset
dataset_root: '/workspace/data/data_folder/o2o/gifs_11_features_vsgnet'

# relative location of the annotations file
device: 'cuda:3'

gif_size: 11

loss_calculation: 'masked loss ican'
comments: 'None'

# wandb_configs
wandb_project_name: 'ooi_icra_ican'
wandb_entity: 'aunmesh'

log_results: False

streams: ['visual', 'spatial', 'combined']

roi_pool_size: [7, 7]
spatial_scale: 1
sampling_ratio: 1


# Neural Network dimensions
gnn_dimensions : [512, 512]
lin_obj_dim : [1024, 1024]

spatial_branch_cr_classifier_dimension : [512, 3]
spatial_branch_lr_classifier_dimension : [512, 5]
spatial_branch_mr_classifier_dimension : [512, 14]

visual_branch_cr_classifier_dimension : [1024, 3]
visual_branch_lr_classifier_dimension : [1024, 5]
visual_branch_mr_classifier_dimension : [1024, 14]

gnn_dropout : 0.15