train_batch_size: 32
val_batch_size: 32
test_batch_size: 32

num_epochs: 20
lr: .001

features_list: ['object_i3d_feature', 'bbox_CLIP', 'geometric_feature',
                'object_semantic_embeddings', 'object_centric_shape_feats']

relative_features_list: ['relative_spatial_feature', 'interaction_bbox_CLIP', 
                        'interaction_centric_shape_feats']


custom_filter_dict:

    'geometric_feature':
      frame_dim : 1
      frame_index : 5

    'object_centric_shape_feats':
      frame_dim : 1
      frame_index : 5

    'object_i3d_feature':
      frame_dim : 0
      frame_index : 2

    'motion_feature':
      frame_dim : 1
      frame_index : 5


optimizer: 'Adam'

# After how many epochs to save the model
save_epoch: 5

loss: 'masked loss'

model_name: 'imp'

overfit: False

model_saving_path: '/workspace/work/results_ICRA_gpnn/'

cr_dimensions : [256, 3]
cr_dropout : 0.15

lr_dimensions : [256, 5]
lr_dropout : 0.15

mr_dimensions : [256, 14]
mr_dropout : 0.15
aggregator : 'mean'

# field to distinguish from different datasets (depending on gif length)
device: 'cuda:2'

# root folder of the dataset
full_dataset_location: '/workspace/data/data_folder/o2o/ral_features/formatted_features/revise_resubmit_v4.pkl'
split_dict_location: '/workspace/data/data_folder/o2o/split_dict.pkl'


loss_calculation: 'masked'
comments: 'None'

# wandb_configs
wandb_project_name: 'revise_resubmit_imp'
wandb_entity: 'aunmesh'

log_results: True
streams: ['combined']

best_model_selection_key: 'val_combined_mAP_all'

edge_feature_size: 1087
node_feature_size: 3130
