train_batch_size: 32
val_batch_size: 32
test_batch_size: 32

num_epochs: 20
lr: .001
features_list: ['object_i3d_feature', 'bbox_CLIP', 'geometric_feature',
                'object_semantic_embeddings', 'object_centric_shape_feats']

relative_features_list: ['relative_spatial_feature', 'interaction_bbox_CLIP', 
                        'interaction_centric_shape_feats']


custom_filter_dict:

    'geometric_feature':
      frame_dim : 1
      frame_index : 5

    'object_centric_shape_feats':
      frame_dim : 1
      frame_index : 5

    'object_i3d_feature':
      frame_dim : 0
      frame_index : 2

    'motion_feature':
      frame_dim : 1
      frame_index : 5


optimizer: 'Adam'

# After how many epochs to save the model
save_epoch: 5

loss: 'masked loss'

model_name: 'graph_rcnn'
GNN: 'GATv2Conv'
# GNN: 'GATv2Conv'


overfit: False

model_saving_path: '/workspace/work/results_ICRA_gpnn/'

# Neural Network dimensions
rel_pn_dimensions : [3130, 256]

edge_feature_size: 1087
node_feature_size: 3130


#gnn_dimensions: [4206, 512, 256, 128, 64]
gnn_dimensions: [512, 256] #, 128, 64, 32]
gnn_dropout : 0.15

cr_dimensions : [512, 3]
cr_dropout : 0.15

lr_dimensions : [512, 5]
lr_dropout : 0.15

mr_dimensions : [512, 14]
mr_dropout : 0.15
aggregator : 'mean'

# field to distinguish from different datasets (depending on gif length)
device: 'cuda:0'

# root folder of the dataset
full_dataset_location: '/workspace/data/data_folder/o2o/ral_features/formatted_features/revise_resubmit_v5.pkl'
split_dict_location: '/workspace/data/data_folder/o2o/split_dict.pkl'

gif_size: 11

loss_calculation: 'masked'
comments: 'None'

# wandb_configs
wandb_project_name: 'resubmit_graph_rcnn'
wandb_entity: 'aunmesh'

log_results: True
streams: ['combined']

best_model_selection_key: 'val_combined_mAP_all'